version: 2
jobs:
  rubocop:
    parameters:
      ruby:
        type: string
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: gem install rubocop
      - run: rubocop

  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose run bbt

workflows:
  version: 2
  ui_testing:
    jobs:
      - rubocop
      - build

